name: animations_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  rive: ^0.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - lib/images/logo_flutter.jpg
  - lib/images/Greek Cities/Athens.jpg
  - lib/images/Greek Cities/Corfou.jpg
  - lib/images/Greek Cities/Delphi.jpg
  - lib/images/Greek Cities/Meteores.jpg
  - lib/images/Greek Cities/Santorin.jpg
  - lib/images/Greek Cities/Sounion.jpg
  - lib/images/tinder/images.jpg
  - lib/images/tinder/images (1).jpg
  - lib/images/tinder/images (2).jpg
  - lib/images/tinder/images (3).jpg
  - lib/images/tinder/images (4).jpg
  - lib/rive/2063-4080-flutter-puzzle-hack-project.riv
  - lib/rive/3257-6868-404.riv
  - lib/images/acceuil/kisspng-car-clip-art-audi-q3-car-5a74c1dadf5c36.7852431415176012429149.png
  - lib/images/acceuil/pexels-jhovani-morales-12319900.jpg

